pipeline {
  agent any

  environment {
      SEE_ENVIRONMENT_PREPARE='if you want to know secrets'
      // https://api.slack.com/apps/AQSDLPATU/incoming-webhooks?success=1
  }

  stages {
    stage('Grab Utility Repo') {
      agent any
      steps {
        //cleanWs()
        //sh("printenv")
        script {
          sh 'pwd'
          sh "echo ${WORKSPACE}"
          sh "cd ${WORKSPACE}"
          sh 'pwd'
          sh 'ls -latr'
          sh 'git branch'
          sh 'git config --local credential.helper "!p() { echo username=\\$GIT_USERNAME; echo password=\\$GIT_PASSWORD; }; p"'

          env.DATETIMESTAMP = sh(returnStdout: true, script: "echo \$(date '+%Y%m%d-%H%M%S')").trim()
          env.JUST_BRANCH_NAME = "${env.GIT_BRANCH}".replace("origin/","")
          env.REL_LOG_PATH = "tests/history/test_${env.DATETIMESTAMP}_" +
                              "${env.JUST_BRANCH_NAME}" +
                              "_${env.GIT_COMMIT}.txt"
          env.GIT_COMMIT_URL = "${env.GIT_URL}".replace(".git","/commit/")+"${env.GIT_COMMIT}"
          env.LOG_PATH_URL = "${env.GIT_URL}".replace(".git","/")+"${env.REL_LOG_PATH}"
        }
      }
    }
    stage('Attach Worker') {
      agent {
        dockerfile { // load python container
          args "--user root -v /var/run/docker.sock:/var/run/docker.sock"
          dir 'tests/docker/dind-python3'
          label 'dind'
        }
      }
      stages {
        stage('Prep environment') {
          agent { label 'dind'}
          steps {
              script {
                  sh 'apk add curl' // for Slack direct curls, no assumed plugin
                  sh "echo 'REL_LOG_PATH: ${env.REL_LOG_PATH}'"
              }
          }
        }
        stage('Get NeoLoad CLI') {
          agent { label 'dind'}
          steps {
              script { // Slack notification: STARTING
                  payload = '{"text":"[STARTING] NeoLoad-CLI build status.\nBranch: '+"${env.GIT_BRANCH}"+'\nSee: '+"${env.BUILD_URL}"+'\nBased on: '+"${env.GIT_COMMIT_URL}"+'"}'
                  sh """curl -s \
                  -X POST -H 'Content-type: application/json' \
                  --data '""" + payload + """' \
                  """ + env.SLACK_URL
                }
              sh "python3 -m pip install -q -e ./"
          }
        }
        stage('Run PyTest') {
          agent { label 'dind'}
          steps {
              // uname adds system name/identity of where this is run for audit
              // parenthesis for uname AND python3 tests into same tee output File
              // tee produces stdout in this same CI output plus a file for checkin
              // exit PIPESTATUS to retain python test exit code for proper pass/fail
              script {
                /*withCredentials([usernamePassword(credentialsId: 'neoload-cli-creds', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')])
                {
                  try {
                    sh """\
                    git init
                    git config --global user.email "jenkins@neotys.oss"
                    git config --global user.name "Jenkins Pipeline"
                    git pull https://""" + "$GIT_USERNAME" + ":" + "$GIT_PASSWORD" + """@github.com/Neotys-Labs/neoload-cli.git """ + "${env.JUST_BRANCH_NAME}" + """
                    """
                    sh """\
                    git branch
                    git status
                    """
                  } catch(Exception ex) {
                    echo "Failed to archive test logs."
                    throw ex
                  }
                }*/
                try {
                  // a lot of this has to do with use of PIPESTATUS and bash exclusivity
                  pipeSubstitution = "\${PIPESTATUS[0]}"
                  tempShellFile = './pytest.temp.sh'
                  shellCommand = """#!/usr/bin/env bash
                      (uname -a && \
                      python3 -m pytest \
                      -v --junitxml=pytest_junit.xml \
                      tests \
                      --xrunslow \
                      ) \
                      | tee \
                      """ + "${env.REL_LOG_PATH}" + """ \
                      ; ( exit """ + pipeSubstitution + """ ) \
                  """
                  while(shellCommand.contains("  ")) shellCommand = shellCommand.replace("  "," ")
                  //echo shellCommand
                  writeFile text: shellCommand, file: tempShellFile
                  sh 'cat ' + tempShellFile
                  sh 'chmod +x ' + tempShellFile
                  sh tempShellFile

                } catch(Exception ex) {
                }
                stash(name:'REL_LOG_PATH', includes: env.REL_LOG_PATH)
                /*
                withCredentials([usernamePassword(credentialsId: 'neoload-cli-creds', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')])
                {
                  // something different
                  try {
                    sh """\
                    git init
                    git config --global user.email "jenkins@neotys.oss"
                    git config --global user.name "Jenkins Pipeline"
                    git pull https://""" + "$GIT_USERNAME" + ":" + "$GIT_PASSWORD" + """@github.com/Neotys-Labs/neoload-cli.git """ + "${env.JUST_BRANCH_NAME}" + """
                    git status
                    git add '""" + "${env.REL_LOG_PATH}" + """'
                    git commit -m 'Auto commit test logs from build """ + "${env.JOB_NAME}" + "#" + "${env.BUILD_NUMBER}" + """'
                    git status
                    git push  """ + "${env.GIT_BRANCH}" + """
                    git status
                    """
                  } catch(Exception ex) {
                    echo "Failed to archive test logs."
                    throw ex
                  }
                }
                */
              }
          }
          post {
              always {
                  junit 'pytest_junit.xml'
              }
          }
        }
      }
    }
    stage('Commit Logs back to Repo') {
      agent any
      steps {
        unstash(name:'REL_LOG_PATH')
        script {
          withCredentials([usernamePassword(credentialsId: 'neoload-cli-creds', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')])
          {
            sh """\
            git status
            git add '""" + "${env.REL_LOG_PATH}" + """'
            git commit -m 'Auto commit test logs from build """ + "${env.JOB_NAME}" + "#" + "${env.BUILD_NUMBER}" + """'
            git status
            git push  """ + "${env.GIT_BRANCH}" + """
            git status
            """
          }
        }
      }
    }
  }
  post {
    always {
        script { // Slack notification: final build status
            payload = '{"text":"[' + "${currentBuild.currentResult}" + '] NeoLoad-CLI build status.\nBranch: '+"${env.GIT_BRANCH}"+'\nSee: '+"${env.BUILD_URL}"+'\nBased on: '+"${env.GIT_COMMIT_URL}"+'\nLogs: '+"${env.LOG_PATH_URL}"+'"}'
            sh """curl -s \
            -X POST -H 'Content-type: application/json' \
            --data '""" + payload + """' \
            """ + env.SLACK_URL
        }
    }
  }
}
