# coding: utf-8

"""
    NeoLoad API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class CounterValues(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'count': 'int',
        'min': 'int',
        'max': 'int',
        'sum': 'int',
        'avg': 'float'
    }

    attribute_map = {
        'count': 'count',
        'min': 'min',
        'max': 'max',
        'sum': 'sum',
        'avg': 'avg'
    }

    def __init__(self, count=None, min=None, max=None, sum=None, avg=None, local_vars_configuration=None):  # noqa: E501
        """CounterValues - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._count = None
        self._min = None
        self._max = None
        self._sum = None
        self._avg = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if min is not None:
            self.min = min
        if max is not None:
            self.max = max
        if sum is not None:
            self.sum = sum
        if avg is not None:
            self.avg = avg

    @property
    def count(self):
        """Gets the count of this CounterValues.  # noqa: E501


        :return: The count of this CounterValues.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this CounterValues.


        :param count: The count of this CounterValues.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def min(self):
        """Gets the min of this CounterValues.  # noqa: E501


        :return: The min of this CounterValues.  # noqa: E501
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this CounterValues.


        :param min: The min of this CounterValues.  # noqa: E501
        :type: int
        """

        self._min = min

    @property
    def max(self):
        """Gets the max of this CounterValues.  # noqa: E501


        :return: The max of this CounterValues.  # noqa: E501
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this CounterValues.


        :param max: The max of this CounterValues.  # noqa: E501
        :type: int
        """

        self._max = max

    @property
    def sum(self):
        """Gets the sum of this CounterValues.  # noqa: E501


        :return: The sum of this CounterValues.  # noqa: E501
        :rtype: int
        """
        return self._sum

    @sum.setter
    def sum(self, sum):
        """Sets the sum of this CounterValues.


        :param sum: The sum of this CounterValues.  # noqa: E501
        :type: int
        """

        self._sum = sum

    @property
    def avg(self):
        """Gets the avg of this CounterValues.  # noqa: E501


        :return: The avg of this CounterValues.  # noqa: E501
        :rtype: float
        """
        return self._avg

    @avg.setter
    def avg(self, avg):
        """Sets the avg of this CounterValues.


        :param avg: The avg of this CounterValues.  # noqa: E501
        :type: float
        """

        self._avg = avg

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CounterValues):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CounterValues):
            return True

        return self.to_dict() != other.to_dict()
