FROM python:3.7-alpine

# add GCC deps, Python (NeoLoad in dev comes later)
RUN apk add -q gcc musl-dev && \
    python3 -m pip install -q --upgrade pip


# for use in CI with a build agent that is a docker host (or connected to one)
ENV DOCKERVERSION=18.03.1-ce
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
 && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 \
                -C /usr/local/bin docker/docker \
 && rm docker-${DOCKERVERSION}.tgz

# copy in current codebase and install CLI
COPY ./ /python_root
RUN rm -rf /python_root/tests /python_root/pipeline_examples && \
    rm -rf /python_root/dist /python_root/build /python_root/.git/python_root/.git*
RUN python3 -m pip install -q -e /python_root

## for local dev purposes only
#$ docker build -t neoload-cli-dev --file resources/docker-neoload-cli/Dockerfile-dev .
#$ docker run --rm neoload-cli-dev neoload --version
#$ docker rmi neoload-cli-dev
