dicotrad = {
 "AUTO_RESERVE": "Auto reserve resources",
 "AUTO_RESERVED": "Auto-reservation completed",
 "GETTING_AVAILABLE_CONTROLLERS": "Controller preparation",
 "GETTING_AVAILABLE_LGS": "Load generators preparation",
 "DOWNLOADING_PROJECT": "Sending project to controller",
 "PUBLISHING_INFRASTRUCTURE": "Sending load generators details to controller",
 "DOWNLOADING_ASCODE_FILE": "Sending additional as-code file",
 "STARTING_BENCH": "Starting infrastructure and test",
 "STARTED_BENCH": "Test started",
 "CANCELLED_BENCH": "Test cancelled",
 "ERROR_NO_MORE_CONTROLLER_CANDIDATE": "No controller agents available in the selected zone",
 "ERROR_NO_MORE_LG_CANDIDATE": "No load generator agents available in the selected zones",
 "ERROR_MAX_RETRY_REACHED": "Too many attempts have been done, please try again",
 "ERROR_UNEXPECTED_BEHAVIOR": "An unexpected error occurred",
 "ERROR_LG_NOT_ENOUGH_SAME_VERSION": "Not enough resources available with the same version",
 "ERROR_AUTO_RESERVATION_FAILED": "Auto-reservation failed",
 "ERROR_ZONE_DELETED": "Test launch aborted: Controller or LG Zone(s) have been deleted.",
 "ERROR_FETCHING_PROJECT_PASSPHRASE": "Unable to retrieve the configured password.",
 "INITIALIZED": "Initialization",
 "CHECKING_AUTO_RESERVATION": "Checking auto-reservation status",
 "SELECTING_VERSION": "Selecting version",
 "ELECTING_CONTROLLER": "Electing controller",
 "LOCKING_CONTROLLER": "Locking controller",
 "CHECKING_CONTROLLER_LOCK": "checking controller",
 "ELECTING_LG": "Electing LG",
 "CHECKING_DOWNLOADED_PROJECT": "Checking downloaded project",
 "DOWNLOADING_INFRASTRUCTURE": "Downloading infrastructure",
 "CHECKING_DOWNLOADED_INFRASTRUCTURE": "Checking downloaded infrastructure",
 "CHECKING_STARTED_BENCH": "Checking started bench", "RETRIEVING_LOGS": "Retrieving logs"
 }