name: Python integration tests

# on: workflow_dispatch
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install jq
    - name: Test with integration script
      run: |
        pwd
        ls -al
        ls -al tests/integration
        ls -al tests/integration/scripts
        ./tests/integration/runAllScripts.sh ${{ secrets.NLWEB_API_URL }} ${{ secrets.NLWEB_TOKEN }}
